name: Project checks

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  policy:
    uses: petohorvath/nixos-project-policy/.github/workflows/check.yml@6208eb8c11a338a96e07002dc45696a5e32abad8
    with:
      project: nixos-cross-config
      policy_revision: 6208eb8c11a338a96e07002dc45696a5e32abad8
