name: Project checks

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  policy:
    uses: petohorvath/nixos-project-policy/.github/workflows/check.yml@eecc24f9b1e87943d0266ef60c835a5ad35c78b7
    with:
      project: nixos-cross-config
      policy_revision: eecc24f9b1e87943d0266ef60c835a5ad35c78b7
